

#define BLOCK_LOG_SIZE 0
#define BLOCKS_PER_GROUP (BLOCK_SIZE*8)
#define FIRST_DATA_BLOCK 1
#define R_BLOCKS_COUNT 0
#define PREALLOC_BLOCKS 0
#define PREALLOC_DIR_BLOCKS 0
#define CAPACITY_PER_INODE (BLOCK_SIZE*2)


