
// 移植完毕
#define BLOCK_LOG_SIZE_EXT2 0
#define BLOCKS_PER_GROUP_EXT2 (BLOCK_SIZE_EXT2*8)
#define FIRST_DATA_BLOCK_EXT2 1
#define R_BLOCKS_COUNT_EXT2 0
#define PREALLOC_BLOCKS_EXT2 0
#define PREALLOC_DIR_BLOCKS_EXT2 0
#define CAPACITY_PER_INODE_EXT2 (BLOCK_SIZE_EXT2*2)


